"""
YOLO Annotation Tool for single-class bounding box labeling.

Reads captures from ./captures/, lets you draw bounding boxes,
and exports a YOLO-format dataset to ./dataset/.

Output structure (ready for Ultralytics YOLO11n training):
    dataset/
    ├── images/             ← annotated images copied here
    ├── labels/             ← one .txt per image (YOLO format)
    ├── splits/             ← train.txt / val.txt (generated by train.py)
    └── data.yaml           ← dataset config

YOLO label format per line:
    <class_id> <x_center> <y_center> <width> <height>
    All values normalized 0..1.  Class 0 = your single target class.

Controls:
    Left-click + drag   : draw bounding box (auto-saves immediately)
    Right-click on box  : delete that box (auto-saves immediately)
    A / ← / Left Arrow  : previous image
    D / → / Right Arrow : next image
    Space               : skip — marks image as having no class (empty annotation)
    Z                   : undo last box
    C                   : clear all boxes from current image
    Escape              : quit

    Auto-advance checkbox: when enabled, drawing a box auto-moves to next image.
"""

import os
import sys
import json
import shutil
import base64
import io
import threading
import tkinter as tk
from tkinter import ttk, messagebox
from PIL import Image, ImageTk, ImageDraw, ImageFont
from pathlib import Path

try:
    import requests as _requests
    _HAS_REQUESTS = True
except ImportError:
    _HAS_REQUESTS = False

try:
    from ultralytics import YOLO as _YOLO
    _HAS_YOLO = True
except ImportError:
    _HAS_YOLO = False

# ── Configuration ──────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).parent.resolve()
CAPTURES_DIR = BASE_DIR / "captures"
DATASET_DIR = BASE_DIR / "dataset"
IMAGES_DIR = DATASET_DIR / "images"
LABELS_DIR = DATASET_DIR / "labels"
PROGRESS_FILE = DATASET_DIR / ".annotation_progress.json"
INFERENCE_CACHE_FILE = DATASET_DIR / ".inference_cache.json"
PRE_ANNOTATION_FILE = DATASET_DIR / ".pre_annotation.json"

CLASS_ID = 0
CLASS_NAME = "target"  # Change this to your actual class name

# Display settings
CANVAS_MAX_W = 1600
CANVAS_MAX_H = 1000
BOX_COLOR = "#00ff00"
BOX_COLOR_SELECTED = "#ff4444"
PREDICTION_COLOR = "#00cccc"   # teal overlay for model predictions
BOX_WIDTH = 2
PREDICTION_CONF_THRESH = 0.25   # minimum confidence to show prediction box

# Path to trained model weights
MODEL_WEIGHTS = BASE_DIR / "models" / "best.pt"

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

# LLM Vision QA settings
LLM_BASE_URL = os.getenv(
    "ARENA_AI_LLM_BASE_URL",
    "http://127.0.0.1:8001",
).rstrip("/")
LLM_MODEL = os.getenv(
    "ARENA_AI_LLM_MODEL",
    "Qwen/Qwen2.5-VL-32B-Instruct-AWQ",
)
LLM_QA_PROMPT = (
    "You are an annotation quality assessor for a video game object detection dataset. "
    "The green bounding boxes drawn on this image are annotations that should tightly "
    "enclose the HEAD of a character (person) in a video game.\n\n"
    "Rate the annotation quality on a scale of 1 to 10:\n"
    "  10 = Box is perfectly placed, tightly fitting the character's head\n"
    "  7-9 = Box is on the head but slightly too large, small, or offset\n"
    "  4-6 = Box partially covers the head but is noticeably misaligned or wrong size\n"
    "  1-3 = Box is not on a character's head at all, or completely wrong\n"
    "  1 = No head visible or box is on a totally irrelevant area\n\n"
    "If there are no green boxes in the image, respond with score 0.\n\n"
    "Respond with ONLY a JSON object in this exact format, nothing else:\n"
    '{\"score\": <number>, \"reason\": \"<one sentence explanation>\"}'
)
LLM_HEAD_DETECT_PROMPT = (
    "You are analyzing a screenshot from a first-person shooter video game. "
    "Your job is to determine whether any enemy player's HEAD is visible in this image.\n\n"
    "Look carefully for context clues:\n"
    "- Player character bodies, shoulders, arms holding weapons\n"
    "- Helmets, hair, or any head-shaped silhouette on top of a body\n"
    "- Partially visible heads peeking around corners or cover\n"
    "- Small or distant heads that might be easy to miss\n\n"
    "Rate the likelihood that a player's head is visible on a scale of 0 to 10:\n"
    "  10 = A head is clearly and obviously visible\n"
    "  7-9 = Very likely a head is present (body visible, head area identifiable)\n"
    "  4-6 = Possibly a head — something that could be a player but uncertain\n"
    "  1-3 = Unlikely — maybe distant shapes or ambiguous objects\n"
    "  0 = No players or heads visible at all (empty scene, sky, terrain only)\n\n"
    "Respond with ONLY a JSON object in this exact format, nothing else:\n"
    '{\"score\": <number>, \"reason\": \"<one sentence explanation>\"}'
)


# ── Progress tracker ──────────────────────────────────────────────────────────
class ProgressTracker:
    """Tracks which images have been annotated to avoid re-work."""

    def __init__(self, progress_file: Path):
        self.path = progress_file
        self.data: dict = {"annotated": {}, "skipped": []}
        self._load()

    def _load(self):
        if self.path.exists():
            with open(self.path, "r") as f:
                self.data = json.load(f)
            # Ensure keys exist
            self.data.setdefault("annotated", {})
            self.data.setdefault("skipped", [])

    def save(self):
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.path, "w") as f:
            json.dump(self.data, f, indent=2)

    def is_annotated(self, filename: str) -> bool:
        return filename in self.data["annotated"]

    def mark_annotated(self, filename: str, num_boxes: int):
        self.data["annotated"][filename] = {"boxes": num_boxes}
        if filename in self.data["skipped"]:
            self.data["skipped"].remove(filename)
        self.save()

    def unmark(self, filename: str):
        self.data["annotated"].pop(filename, None)
        self.save()

    @property
    def annotated_count(self) -> int:
        return len(self.data["annotated"])


# ── Inference Cache ───────────────────────────────────────────────────────────
class InferenceCache:
    """Caches model predictions per image, persisted to disk.

    Invalidates automatically when the model path changes.
    """

    def __init__(self, cache_file: Path, model_path: Path):
        self.path = cache_file
        self.model_key = str(model_path)
        self.predictions: dict[str, list] = {}  # filename -> [[x1,y1,x2,y2,conf], ...]
        self._load()

    def _load(self):
        if self.path.exists():
            with open(self.path, "r") as f:
                data = json.load(f)
            if data.get("model_path") == self.model_key:
                self.predictions = data.get("predictions", {})
            else:
                print("Model changed — inference cache invalidated.")
                self.predictions = {}

    def save(self):
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.path, "w") as f:
            json.dump({
                "model_path": self.model_key,
                "predictions": self.predictions,
            }, f)

    def get(self, filename: str) -> list | None:
        return self.predictions.get(filename)

    def has(self, filename: str) -> bool:
        return filename in self.predictions

    def put(self, filename: str, preds: list):
        self.predictions[filename] = preds


# ── Pre-Annotation Cache ─────────────────────────────────────────────────────
class PreAnnotationCache:
    """Stores LLM pre-annotation scores per image.

    Each entry: {mode: "qa"|"detect", score: 0-10, reason: str, has_detections: bool}
    """

    def __init__(self, cache_file: Path):
        self.path = cache_file
        self.entries: dict[str, dict] = {}
        self._load()

    def _load(self):
        if self.path.exists():
            with open(self.path, "r") as f:
                self.entries = json.load(f)

    def save(self):
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.path, "w") as f:
            json.dump(self.entries, f, indent=1)

    def get(self, filename: str) -> dict | None:
        return self.entries.get(filename)

    def has(self, filename: str) -> bool:
        return filename in self.entries

    def put(self, filename: str, mode: str, score: int, reason: str, has_detections: bool):
        self.entries[filename] = {
            "mode": mode,
            "score": score,
            "reason": reason,
            "has_detections": has_detections,
        }

    @property
    def count(self) -> int:
        return len(self.entries)


# ── Annotation Tool GUI ──────────────────────────────────────────────────────
class AnnotationTool:
    def __init__(self):
        # Ensure directories exist
        CAPTURES_DIR.mkdir(parents=True, exist_ok=True)
        IMAGES_DIR.mkdir(parents=True, exist_ok=True)
        LABELS_DIR.mkdir(parents=True, exist_ok=True)

        self.progress = ProgressTracker(PROGRESS_FILE)

        # Gather image list from captures
        self.image_files: list[str] = sorted(
            f for f in os.listdir(CAPTURES_DIR)
            if Path(f).suffix.lower() in IMAGE_EXTENSIONS
        )

        if not self.image_files:
            print("No images found in captures/ directory.")
            print("Run capture.py first to collect screenshots.")
            sys.exit(1)

        self.current_index = 0
        self.boxes: list[list[float]] = []  # Each box: [x1, y1, x2, y2] in pixel coords
        self.drawing = False
        self.draw_start = None
        self.current_rect_id = None
        self.scale = 1.0  # display scale factor
        self.img_w = 0
        self.img_h = 0
        self._mouse_x = 0  # last known mouse position on canvas
        self._mouse_y = 0
        self.predictions: list[tuple[float, float, float, float, float]] = []  # (x1,y1,x2,y2,conf)
        self._advance_timer = None  # pending auto-advance after id
        self._llm_qa_score: int | None = None  # latest LLM QA score (1-10)
        self._llm_qa_reason: str = ""           # latest LLM QA reason
        self._llm_qa_mode: str = "qa"           # "qa" or "detect"
        self._filtered_files: list[str] = []    # current filtered view (subset of image_files)
        self._active_filter: str = "All images" # active filter key
        self._active_filter_display: str = "All images"  # display label with count
        self._display_to_key: dict[str, str] = {}  # display label -> filter key

        # Load YOLO model for prediction overlay
        self.model = None
        if _HAS_YOLO and MODEL_WEIGHTS.exists():
            print(f"Loading model: {MODEL_WEIGHTS}")
            self.model = _YOLO(str(MODEL_WEIGHTS))
            print("Model loaded – predictions will appear as teal boxes")
        else:
            if not _HAS_YOLO:
                print("ultralytics not installed – prediction overlay disabled")
            elif not MODEL_WEIGHTS.exists():
                print(f"Model not found at {MODEL_WEIGHTS} – prediction overlay disabled")

        # Initialize inference cache (persists predictions to disk)
        # Load cache even without model — cached predictions still display as teal boxes
        self.inference_cache = None
        if self.model is not None:
            self.inference_cache = InferenceCache(INFERENCE_CACHE_FILE, MODEL_WEIGHTS)
        elif INFERENCE_CACHE_FILE.exists():
            self.inference_cache = InferenceCache(INFERENCE_CACHE_FILE, MODEL_WEIGHTS)

        # Initialize pre-annotation cache (LLM scores)
        self.pre_annotation = PreAnnotationCache(PRE_ANNOTATION_FILE)

        self._build_gui()

        # Pre-infer all images (shows progress bar, uses cache for already-done)
        if self.model is not None:
            self._run_pre_inference()

        # Show startup stats and offer pre-annotation
        self._show_startup_dialog()

        # Apply initial filter (show all)
        self._apply_image_filter()

    def _run_pre_inference(self):
        """Run model inference on unannotated images not yet in cache, with a progress bar."""
        to_infer = [
            f for f in self.image_files
            if not self.inference_cache.has(f) and not self.progress.is_annotated(f)
        ]
        if not to_infer:
            print(f"Inference cache up-to-date ({len(self.image_files)} images cached).")
            return

        total = len(to_infer)
        print(f"Pre-inferencing {total} images...")

        # Progress dialog
        progress_win = tk.Toplevel(self.root)
        progress_win.title("Pre-inference")
        progress_win.configure(bg="#2b2b2b")
        progress_win.geometry("520x130")
        progress_win.resizable(False, False)
        progress_win.transient(self.root)
        progress_win.grab_set()

        tk.Label(
            progress_win, text="Running AI inference on unannotated images...",
            font=("Consolas", 11), bg="#2b2b2b", fg="#ffffff",
        ).pack(pady=(15, 5))

        progress_var = tk.DoubleVar(value=0)
        progress_bar = ttk.Progressbar(
            progress_win, variable=progress_var, maximum=total, length=460,
        )
        progress_bar.pack(pady=5)

        status_label = tk.Label(
            progress_win, text=f"0 / {total}",
            font=("Consolas", 10), bg="#2b2b2b", fg="#aaaaaa",
        )
        status_label.pack()

        for idx, fname in enumerate(to_infer):
            filepath = CAPTURES_DIR / fname
            results = self.model(filepath, imgsz=640, conf=PREDICTION_CONF_THRESH, verbose=False)
            preds = []
            for r in results:
                for box in r.boxes:
                    x1, y1, x2, y2 = box.xyxy[0].tolist()
                    conf = box.conf[0].item()
                    preds.append([x1, y1, x2, y2, conf])
            self.inference_cache.put(fname, preds)

            progress_var.set(idx + 1)
            status_label.config(text=f"{idx + 1} / {total}")
            progress_win.update()

            # Periodic disk save every 100 images
            if (idx + 1) % 100 == 0:
                self.inference_cache.save()

        self.inference_cache.save()
        progress_win.destroy()
        print(f"Pre-inference complete — {total} images processed.")

    def _show_startup_dialog(self):
        """Show dataset stats and offer to run LLM pre-annotation on un-scored images."""
        if not _HAS_REQUESTS:
            return

        total = len(self.image_files)
        annotated = sum(1 for f in self.image_files if self.progress.is_annotated(f))
        unannotated = total - annotated
        pre_annotated = sum(
            1 for f in self.image_files
            if not self.progress.is_annotated(f) and self.pre_annotation.has(f)
        )
        needs_pre = unannotated - pre_annotated

        print(f"\n  Total images   : {total}")
        print(f"  Annotated      : {annotated}")
        print(f"  Unannotated    : {unannotated}")
        print(f"  Pre-annotated  : {pre_annotated}")
        print(f"  Needs pre-ann  : {needs_pre}\n")

        if needs_pre <= 0:
            print("All unannotated images already have LLM pre-annotation scores.")
            return

        # Ask user
        answer = messagebox.askyesno(
            "Pre-Annotation",
            f"Dataset summary:\n"
            f"  {total} total images\n"
            f"  {annotated} annotated\n"
            f"  {unannotated} unannotated\n"
            f"  {pre_annotated} already pre-annotated\n"
            f"  {needs_pre} need LLM pre-annotation\n\n"
            f"Run LLM pre-annotation on {needs_pre} images now?\n"
            f"(This sends each image to the vision LLM for scoring)",
            parent=self.root,
        )

        if answer:
            self._run_pre_annotation()

    def _run_pre_annotation(self):
        """Run LLM pre-annotation on all unannotated images not yet scored."""
        to_process = [
            f for f in self.image_files
            if not self.progress.is_annotated(f) and not self.pre_annotation.has(f)
        ]
        if not to_process:
            return

        total = len(to_process)
        print(f"Pre-annotating {total} images via LLM...")

        # Progress dialog
        progress_win = tk.Toplevel(self.root)
        progress_win.title("LLM Pre-Annotation")
        progress_win.configure(bg="#2b2b2b")
        progress_win.geometry("600x160")
        progress_win.resizable(False, False)
        progress_win.transient(self.root)
        progress_win.grab_set()

        tk.Label(
            progress_win, text="Scoring images with vision LLM...",
            font=("Consolas", 11), bg="#2b2b2b", fg="#ffffff",
        ).pack(pady=(15, 5))

        progress_var = tk.DoubleVar(value=0)
        progress_bar = ttk.Progressbar(
            progress_win, variable=progress_var, maximum=total, length=540,
        )
        progress_bar.pack(pady=5)

        status_label = tk.Label(
            progress_win, text=f"0 / {total}",
            font=("Consolas", 10), bg="#2b2b2b", fg="#aaaaaa",
        )
        status_label.pack()

        detail_label = tk.Label(
            progress_win, text="",
            font=("Consolas", 9), bg="#2b2b2b", fg="#666666",
        )
        detail_label.pack()

        errors = 0
        for idx, fname in enumerate(to_process):
            filepath = CAPTURES_DIR / fname

            # Determine mode: does the YOLO model have detections for this image?
            has_dets = False
            if self.inference_cache is not None:
                cached = self.inference_cache.get(fname)
                if cached and len(cached) > 0:
                    has_dets = True

            # Build the image to send
            pil_img = Image.open(filepath).convert("RGB")
            if has_dets:
                # Draw prediction boxes on the image like the annotation tool does
                draw = ImageDraw.Draw(pil_img)
                for x1, y1, x2, y2, conf in cached:
                    draw.rectangle([x1, y1, x2, y2], outline=(0, 204, 204), width=2)
                    draw.text((x1 + 2, y1 - 12), f"{conf:.0%}", fill=(0, 204, 204))
                prompt = LLM_QA_PROMPT
                mode = "qa"
            else:
                prompt = LLM_HEAD_DETECT_PROMPT
                mode = "detect"

            # Call LLM (reuse existing method)
            score, reason = self._call_llm_qa(pil_img, prompt)

            if score is not None:
                self.pre_annotation.put(fname, mode, score, reason, has_dets)
            else:
                errors += 1
                # Store error as score -1 so we can retry later
                self.pre_annotation.put(fname, mode, -1, reason, has_dets)

            progress_var.set(idx + 1)
            score_str = f"{score}/10" if score is not None else "err"
            status_label.config(text=f"{idx + 1} / {total}  ({errors} errors)")
            detail_label.config(text=f"{fname}  →  {mode} {score_str}")
            progress_win.update()

            # Periodic save every 25 images
            if (idx + 1) % 25 == 0:
                self.pre_annotation.save()

        self.pre_annotation.save()
        progress_win.destroy()
        print(f"Pre-annotation complete — {total} images scored, {errors} errors.")

    def _build_gui(self):
        self.root = tk.Tk()
        self.root.title("YOLO Annotation Tool")
        self.root.configure(bg="#2b2b2b")

        # Top bar
        top_frame = tk.Frame(self.root, bg="#1e1e1e", padx=10, pady=6)
        top_frame.pack(fill=tk.X)

        self.file_label = tk.Label(
            top_frame, text="", font=("Consolas", 11), bg="#1e1e1e", fg="#ffffff"
        )
        self.file_label.pack(side=tk.LEFT)

        # Pre-annotation filter dropdown
        # Filter keys (stable identifiers used by _apply_image_filter)
        self._filter_keys = [
            "All images",
            "Unannotated only",
            "── Head Detection ──",
            "Heads 9-10 (obvious)",
            "Heads 7-8 (likely)",
            "Heads 4-6 (maybe)",
            "Heads 1-3 (unlikely)",
            "Heads 0 (empty)",
            "── Box Quality (single) ──",
            "QA 1-box 9-10 (perfect)",
            "QA 1-box 7-8 (good)",
            "QA 1-box 4-6 (misaligned)",
            "QA 1-box 1-3 (bad)",
            "── Box Quality (multi) ──",
            "QA multi 9-10 (perfect)",
            "QA multi 7-8 (good)",
            "QA multi 4-6 (misaligned)",
            "QA multi 1-3 (bad)",
            "── Special ──",
            "Not pre-annotated",
            "Errors only",
        ]
        tk.Label(top_frame, text="Filter:", font=("Consolas", 10),
                 bg="#1e1e1e", fg="#aaaaaa").pack(side=tk.LEFT, padx=(15, 3))
        self.filter_var = tk.StringVar(value="All images")
        self.filter_combo = ttk.Combobox(
            top_frame, textvariable=self.filter_var, state="readonly",
            values=self._filter_keys, width=30, font=("Consolas", 10),
            height=25,
        )
        self.filter_combo.pack(side=tk.LEFT, padx=(0, 5))
        self.filter_combo.bind("<<ComboboxSelected>>", lambda e: self._on_filter_change())

        self.filter_count_label = tk.Label(
            top_frame, text="", font=("Consolas", 10, "bold"), bg="#1e1e1e", fg="#00cccc"
        )
        self.filter_count_label.pack(side=tk.LEFT, padx=(0, 10))

        self.status_label = tk.Label(
            top_frame, text="", font=("Consolas", 10), bg="#1e1e1e", fg="#aaaaaa"
        )
        self.status_label.pack(side=tk.RIGHT)

        self.annotated_badge = tk.Label(
            top_frame, text="", font=("Consolas", 10, "bold"), bg="#1e1e1e", fg="#00ff00"
        )
        self.annotated_badge.pack(side=tk.RIGHT, padx=(0, 15))

        # Canvas
        canvas_frame = tk.Frame(self.root, bg="#2b2b2b")
        canvas_frame.pack(fill=tk.BOTH, expand=True, padx=5, pady=5)

        self.canvas = tk.Canvas(
            canvas_frame, bg="#000000", cursor="crosshair",
            highlightthickness=0
        )
        self.canvas.pack(fill=tk.BOTH, expand=True)

        # Bottom bar with buttons
        bottom_frame = tk.Frame(self.root, bg="#1e1e1e", padx=10, pady=6)
        bottom_frame.pack(fill=tk.X)

        btn_style = {"font": ("Consolas", 10), "bg": "#3c3c3c", "fg": "#ffffff",
                      "activebackground": "#555555", "activeforeground": "#ffffff",
                      "relief": tk.FLAT, "padx": 12, "pady": 4}

        tk.Button(bottom_frame, text="◀ Prev (A)", command=self._prev_image, **btn_style).pack(side=tk.LEFT, padx=2)
        tk.Button(bottom_frame, text="Next (D) ▶", command=self._next_image, **btn_style).pack(side=tk.LEFT, padx=2)
        tk.Button(bottom_frame, text="Skip (Space)", command=self._skip_no_class, **btn_style).pack(side=tk.LEFT, padx=2)
        tk.Button(bottom_frame, text="Undo Box (Z)", command=self._undo_last_box, **btn_style).pack(side=tk.LEFT, padx=2)
        tk.Button(bottom_frame, text="Clear All (C)", command=self._clear_boxes, **btn_style).pack(side=tk.LEFT, padx=2)
        tk.Button(bottom_frame, text="Accept AI (Enter)", command=self._accept_predictions, **btn_style).pack(side=tk.LEFT, padx=2)
        tk.Button(bottom_frame, text="Bulk (B)", command=self._open_bulk, **btn_style).pack(side=tk.LEFT, padx=2)

        # Auto-advance toggle
        self.auto_advance = tk.BooleanVar(value=True)
        self.auto_advance_cb = tk.Checkbutton(
            bottom_frame, text="Auto-advance", variable=self.auto_advance,
            font=("Consolas", 10), bg="#1e1e1e", fg="#ffffff",
            selectcolor="#3c3c3c", activebackground="#1e1e1e", activeforeground="#ffffff",
        )
        self.auto_advance_cb.pack(side=tk.LEFT, padx=(20, 2))

        # LLM QA toggle
        self.llm_qa_enabled = tk.BooleanVar(value=False)
        self.llm_qa_cb = tk.Checkbutton(
            bottom_frame, text="LLM QA", variable=self.llm_qa_enabled,
            font=("Consolas", 10), bg="#1e1e1e", fg="#ffffff",
            selectcolor="#3c3c3c", activebackground="#1e1e1e", activeforeground="#ffffff",
            command=self._on_llm_qa_toggle,
        )
        self.llm_qa_cb.pack(side=tk.LEFT, padx=(10, 2))
        if not _HAS_REQUESTS:
            self.llm_qa_cb.config(state=tk.DISABLED)

        # LLM QA score display
        self.llm_score_label = tk.Label(
            bottom_frame, text="", font=("Consolas", 10, "bold"), bg="#1e1e1e", fg="#ff69b4"
        )
        self.llm_score_label.pack(side=tk.LEFT, padx=(5, 0))

        self.counter_label = tk.Label(
            bottom_frame, text="", font=("Consolas", 10), bg="#1e1e1e", fg="#aaaaaa"
        )
        self.counter_label.pack(side=tk.RIGHT)

        self.box_count_label = tk.Label(
            bottom_frame, text="Boxes: 0", font=("Consolas", 10), bg="#1e1e1e", fg="#ffaa00"
        )
        self.box_count_label.pack(side=tk.RIGHT, padx=(0, 15))

        # Mouse bindings
        self.canvas.bind("<ButtonPress-1>", self._on_mouse_down)
        self.canvas.bind("<B1-Motion>", self._on_mouse_drag)
        self.canvas.bind("<ButtonRelease-1>", self._on_mouse_up)
        self.canvas.bind("<ButtonPress-3>", self._on_right_click)

        # Key bindings
        self.root.bind("<KeyPress-a>", lambda e: self._prev_image())
        self.root.bind("<KeyPress-d>", lambda e: self._next_image())
        self.root.bind("<KeyPress-A>", lambda e: self._prev_image())
        self.root.bind("<KeyPress-D>", lambda e: self._next_image())
        self.root.bind("<Left>", lambda e: self._prev_image())
        self.root.bind("<Right>", lambda e: self._next_image())
        self.root.bind("<space>", lambda e: self._skip_no_class())
        self.root.bind("<KeyPress-z>", lambda e: self._undo_last_box())
        self.root.bind("<KeyPress-c>", lambda e: self._clear_boxes())
        self.root.bind("<KeyPress-Z>", lambda e: self._undo_last_box())
        self.root.bind("<KeyPress-C>", lambda e: self._clear_boxes())
        self.root.bind("<Return>", lambda e: self._accept_predictions())
        self.root.bind("<Shift_L>", lambda e: self._accept_hovered_prediction())
        self.root.bind("<Shift_R>", lambda e: self._accept_hovered_prediction())
        self.root.bind("<KeyPress-b>", lambda e: self._open_bulk())
        self.root.bind("<KeyPress-B>", lambda e: self._open_bulk())
        self.root.bind("<Escape>", lambda e: self.root.quit())
        # Ctrl hold = multi-box mode (suppress auto-advance)
        self._multi_box_mode = False
        self.root.bind("<KeyPress-Control_L>", lambda e: setattr(self, '_multi_box_mode', True))
        self.root.bind("<KeyRelease-Control_L>", lambda e: setattr(self, '_multi_box_mode', False))
        self.root.bind("<KeyPress-Control_R>", lambda e: setattr(self, '_multi_box_mode', True))
        self.root.bind("<KeyRelease-Control_R>", lambda e: setattr(self, '_multi_box_mode', False))

        # Keep keyboard focus on root so key bindings always fire
        self.root.focus_set()
        self.canvas.bind("<Motion>", self._on_mouse_move)
        self.canvas.bind("<ButtonPress-1>", self._on_mouse_down_refocus)

    # ── Image filter ─────────────────────────────────────────────────────

    def _on_filter_change(self):
        """Handle filter dropdown selection."""
        selected = self.filter_var.get()
        # Map display label (with count) back to the filter key
        key = self._display_to_key.get(selected, selected)
        # Ignore separator lines
        if key.startswith("──"):
            self.filter_var.set(self._active_filter_display)
            return
        self._active_filter = key
        self._apply_image_filter()
        # Jump to first image in the filtered set
        if self._filtered_files:
            self.current_index = 0
            self._load_image()

    def _match_filter(self, filt: str, fname: str) -> bool:
        """Return True if fname matches the given filter key."""
        is_ann = self.progress.is_annotated(fname)
        pre = self.pre_annotation.get(fname)

        if filt == "All images":
            return True
        elif filt == "Unannotated only":
            return not is_ann
        elif filt == "Not pre-annotated":
            return not is_ann and not self.pre_annotation.has(fname)
        elif filt == "Errors only":
            return bool(pre and pre.get("score", 0) == -1)
        elif filt.startswith("Heads"):
            if is_ann or not pre or pre.get("mode") != "detect":
                return False
            score = pre.get("score", -1)
            if filt == "Heads 9-10 (obvious)":
                return 9 <= score <= 10
            elif filt == "Heads 7-8 (likely)":
                return 7 <= score <= 8
            elif filt == "Heads 4-6 (maybe)":
                return 4 <= score <= 6
            elif filt == "Heads 1-3 (unlikely)":
                return 1 <= score <= 3
            elif filt == "Heads 0 (empty)":
                return score == 0
        elif filt.startswith("QA"):
            if is_ann or not pre or pre.get("mode") != "qa":
                return False
            score = pre.get("score", -1)
            # Determine box count from inference cache
            cached = self.inference_cache.get(fname) if self.inference_cache else None
            nboxes = len(cached) if cached else 0
            is_single = (nboxes == 1)
            is_multi = (nboxes > 1)
            # Check single-box QA filters
            if filt == "QA 1-box 9-10 (perfect)":
                return is_single and 9 <= score <= 10
            elif filt == "QA 1-box 7-8 (good)":
                return is_single and 7 <= score <= 8
            elif filt == "QA 1-box 4-6 (misaligned)":
                return is_single and 4 <= score <= 6
            elif filt == "QA 1-box 1-3 (bad)":
                return is_single and 1 <= score <= 3
            # Check multi-box QA filters
            elif filt == "QA multi 9-10 (perfect)":
                return is_multi and 9 <= score <= 10
            elif filt == "QA multi 7-8 (good)":
                return is_multi and 7 <= score <= 8
            elif filt == "QA multi 4-6 (misaligned)":
                return is_multi and 4 <= score <= 6
            elif filt == "QA multi 1-3 (bad)":
                return is_multi and 1 <= score <= 3
        return False

    def _apply_image_filter(self):
        """Build self._filtered_files based on the active filter and refresh dropdown counts."""
        filt = self._active_filter

        # Single pass: compute counts for all filter keys simultaneously
        non_sep_keys = [k for k in self._filter_keys if not k.startswith("──")]
        counts = {k: 0 for k in non_sep_keys}
        result = []

        for fname in self.image_files:
            for key in non_sep_keys:
                if self._match_filter(key, fname):
                    counts[key] += 1
            if self._match_filter(filt, fname):
                result.append(fname)

        self._filtered_files = result
        count = len(result)
        self.filter_count_label.config(text=f"({count})")

        # Rebuild dropdown labels with counts
        self._display_to_key = {}
        display_labels = []
        for key in self._filter_keys:
            if key.startswith("──"):
                display_labels.append(key)
                self._display_to_key[key] = key
            else:
                n = counts[key]
                label = f"{key}  ({n})"
                display_labels.append(label)
                self._display_to_key[label] = key

        self.filter_combo["values"] = display_labels
        # Update the displayed text to match the active filter with count
        for lbl, k in self._display_to_key.items():
            if k == filt:
                self._active_filter_display = lbl
                self.filter_var.set(lbl)
                break

    # ── LLM QA scoring ────────────────────────────────────────────────────

    def _on_llm_qa_toggle(self):
        """Called when the LLM QA checkbox is toggled."""
        if self.llm_qa_enabled.get():
            self._run_llm_qa()
        else:
            self._llm_qa_score = None
            self._llm_qa_reason = ""
            self.llm_score_label.config(text="")
            self._redraw()

    def _render_image_with_boxes(self) -> Image.Image:
        """Return a PIL image of the current capture with all visible boxes drawn on it.

        Draws both manual annotation boxes (green) and AI prediction boxes (teal)
        so the VLM sees exactly what's on screen.
        """
        filename = self._filtered_files[self.current_index]
        filepath = self._resolve_image_path(filename)
        pil_img = Image.open(filepath).convert("RGB")
        draw = ImageDraw.Draw(pil_img)

        # Draw AI prediction boxes (teal, same as canvas overlay)
        for x1, y1, x2, y2, conf in self.predictions:
            draw.rectangle([x1, y1, x2, y2], outline=(0, 204, 204), width=2)
            draw.text((x1 + 2, y1 - 12), f"{conf:.0%}", fill=(0, 204, 204))

        # Draw manual annotation boxes (green)
        for box in self.boxes:
            x1, y1, x2, y2 = box
            draw.rectangle([x1, y1, x2, y2], outline=(0, 255, 0), width=3)
            draw.text((x1 + 2, y1 - 12), CLASS_NAME, fill=(0, 255, 0))

        return pil_img

    def _run_llm_qa(self):
        """Send the current annotated image to the VLM for quality scoring (async)."""
        if not _HAS_REQUESTS:
            return

        has_boxes = bool(self.boxes or self.predictions)

        # Choose prompt and image based on whether boxes are present
        if has_boxes:
            prompt = LLM_QA_PROMPT
            img = self._render_image_with_boxes()
            self._llm_qa_mode = "qa"  # annotation quality mode
        else:
            prompt = LLM_HEAD_DETECT_PROMPT
            # Send the raw image — no boxes to draw
            filename = self._filtered_files[self.current_index]
            filepath = self._resolve_image_path(filename)
            img = Image.open(filepath).convert("RGB")
            self._llm_qa_mode = "detect"  # head detection mode

        # Show loading state
        self.llm_score_label.config(text="QA: ...", fg="#aaaaaa")
        self._llm_qa_score = None
        self._llm_qa_reason = ""

        current_idx = self.current_index

        def _query():
            try:
                score, reason = self._call_llm_qa(img, prompt)
            except Exception as e:
                score, reason = None, f"Thread error: {e}"
            self.root.after(0, lambda: self._on_llm_qa_result(current_idx, score, reason))

        threading.Thread(target=_query, daemon=True).start()

    def _call_llm_qa(self, img: Image.Image, prompt: str) -> tuple[int | None, str]:
        """Send the image to the VLM and parse the score. Runs in a background thread."""
        try:
            # Encode image to base64 JPEG
            buf = io.BytesIO()
            img.save(buf, format="JPEG", quality=85)
            img_b64 = base64.b64encode(buf.getvalue()).decode("utf-8")

            payload = {
                "model": LLM_MODEL,
                "messages": [
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": f"data:image/jpeg;base64,{img_b64}"
                                },
                            },
                            {
                                "type": "text",
                                "text": prompt,
                            },
                        ],
                    }
                ],
                "temperature": 0.3,
                "max_tokens": 256,
                "chat_template_kwargs": {"enable_thinking": False},
            }

            resp = _requests.post(
                f"{LLM_BASE_URL}/v1/chat/completions",
                json=payload,
                timeout=60,
            )
            resp.raise_for_status()
            data = resp.json()
            content = data["choices"][0]["message"]["content"].strip()

            # Parse JSON from response (handle markdown code fences)
            if content.startswith("```"):
                # Strip ```json ... ```
                lines = content.split("\n")
                content = "\n".join(
                    l for l in lines if not l.strip().startswith("```")
                )

            result = json.loads(content)
            score = int(result.get("score", 0))
            score = max(0, min(10, score))
            reason = str(result.get("reason", ""))
            return score, reason

        except (json.JSONDecodeError, KeyError, ValueError) as e:
            return None, f"Parse error: {e}"
        except _requests.RequestException as e:
            return None, f"Request error: {e}"

    def _on_llm_qa_result(self, for_index: int, score: int | None, reason: str):
        """Handle the LLM QA result on the main thread."""
        # Ignore stale results if user navigated away
        if self.current_index != for_index or not self.llm_qa_enabled.get():
            return

        self._llm_qa_score = score
        self._llm_qa_reason = reason

        if score is not None:
            # Color-code the score
            if score >= 8:
                color = "#00ff00"  # green — great
            elif score >= 5:
                color = "#ffaa00"  # orange — okay
            else:
                color = "#ff4444"  # red — bad

            mode = getattr(self, '_llm_qa_mode', 'qa')
            if mode == "detect":
                label = f"Head?: {score}/10"
            else:
                label = f"QA: {score}/10"
            self.llm_score_label.config(text=label, fg=color)
        else:
            self.llm_score_label.config(text=f"QA: err", fg="#ff4444")

        self._redraw()

    def _load_image(self):
        """Load the current image and any existing annotations."""
        filename = self._filtered_files[self.current_index]
        filepath = self._resolve_image_path(filename)

        # Load image with PIL
        pil_img = Image.open(filepath)
        self.img_w, self.img_h = pil_img.size

        # Compute scale to fit canvas (allows upscaling for small images)
        self.root.update_idletasks()
        scale_w = CANVAS_MAX_W / self.img_w
        scale_h = CANVAS_MAX_H / self.img_h
        self.scale = min(scale_w, scale_h)

        display_w = int(self.img_w * self.scale)
        display_h = int(self.img_h * self.scale)

        # Resize for display (up or down)
        if self.scale != 1.0:
            display_img = pil_img.resize((display_w, display_h), Image.LANCZOS)
        else:
            display_img = pil_img

        self.tk_img = ImageTk.PhotoImage(display_img)

        # Configure canvas size
        self.canvas.config(width=display_w, height=display_h)

        # Load existing annotations if any
        self.boxes = []
        label_path = LABELS_DIR / (Path(filename).stem + ".txt")
        if label_path.exists():
            self._load_yolo_labels(label_path)

        # Use cached predictions for overlay
        self.predictions = []
        if self.inference_cache is not None:
            cached = self.inference_cache.get(filename)
            if cached:
                self.predictions = [tuple(p) for p in cached]

        # Update display
        self._redraw()
        self._update_labels()

        # Trigger LLM QA if enabled
        self._llm_qa_score = None
        self._llm_qa_reason = ""
        self.llm_score_label.config(text="")
        if self.llm_qa_enabled.get():
            self._run_llm_qa()

    def _load_yolo_labels(self, label_path: Path):
        """Load YOLO format labels back into pixel coordinates."""
        with open(label_path, "r") as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) != 5:
                    continue
                _, xc, yc, w, h = map(float, parts)
                # Convert normalized center+size to pixel x1,y1,x2,y2
                x1 = (xc - w / 2) * self.img_w
                y1 = (yc - h / 2) * self.img_h
                x2 = (xc + w / 2) * self.img_w
                y2 = (yc + h / 2) * self.img_h
                self.boxes.append([x1, y1, x2, y2])

    def _redraw(self):
        """Redraw the canvas with current image and all boxes."""
        self.canvas.delete("all")
        self.canvas.create_image(0, 0, anchor=tk.NW, image=self.tk_img)

        # Draw teal prediction boxes (model overlay, display-only)
        for j, pred in enumerate(self.predictions):
            px1, py1, px2, py2, conf = pred
            px1, py1, px2, py2 = [c * self.scale for c in (px1, py1, px2, py2)]
            self.canvas.create_rectangle(
                px1, py1, px2, py2,
                outline=PREDICTION_COLOR, width=1, dash=(6, 3),
                tags=f"pred_{j}"
            )
            self.canvas.create_text(
                px1 + 3, py1 - 3, anchor=tk.SW,
                text=f"{conf:.0%}", font=("Consolas", 8),
                fill=PREDICTION_COLOR, tags=f"predlbl_{j}"
            )

        # Draw annotation boxes (green, these are the real labels)
        for i, box in enumerate(self.boxes):
            x1, y1, x2, y2 = [c * self.scale for c in box]
            self.canvas.create_rectangle(
                x1, y1, x2, y2,
                outline=BOX_COLOR, width=BOX_WIDTH, tags=f"box_{i}"
            )
            # Draw small label
            self.canvas.create_text(
                x1 + 3, y1 - 3, anchor=tk.SW,
                text=f"{CLASS_NAME}", font=("Consolas", 9),
                fill=BOX_COLOR, tags=f"label_{i}"
            )

        self.box_count_label.config(text=f"Boxes: {len(self.boxes)}")

        # Draw cached pre-annotation score (top-left, always visible)
        filename = self._filtered_files[self.current_index]
        pre = self.pre_annotation.get(filename)
        if pre and pre.get("score", -1) >= 0:
            ps = pre["score"]
            pm = pre.get("mode", "?")
            if ps >= 8:
                pc = "#00ff00"
            elif ps >= 5:
                pc = "#ffaa00"
            else:
                pc = "#ff4444"
            plabel = "Head" if pm == "detect" else "QA"
            self.canvas.create_text(
                10, 10, anchor=tk.NW,
                text=f"Pre: {plabel} {ps}/10",
                font=("Consolas", 12, "bold"), fill=pc,
                tags="pre_score"
            )
            if pre.get("reason"):
                self.canvas.create_text(
                    10, 30, anchor=tk.NW,
                    text=pre["reason"][:80],
                    font=("Consolas", 9), fill="#999999",
                    tags="pre_reason"
                )

        # Draw LLM QA score overlay on canvas (top-right corner)
        if self._llm_qa_score is not None and self.llm_qa_enabled.get():
            score = self._llm_qa_score
            if score >= 8:
                score_color = "#00ff00"
            elif score >= 5:
                score_color = "#ffaa00"
            else:
                score_color = "#ff4444"

            display_w = int(self.img_w * self.scale)
            # Score badge
            mode = getattr(self, '_llm_qa_mode', 'qa')
            if mode == "detect":
                score_text = f"Head?: {score}/10"
            else:
                score_text = f"QA: {score}/10"
            self.canvas.create_text(
                display_w - 10, 10, anchor=tk.NE,
                text=score_text,
                font=("Consolas", 16, "bold"), fill=score_color,
                tags="llm_qa_score"
            )
            # Reason text below the score
            if self._llm_qa_reason:
                self.canvas.create_text(
                    display_w - 10, 34, anchor=tk.NE,
                    text=self._llm_qa_reason[:80],
                    font=("Consolas", 9), fill="#cccccc",
                    tags="llm_qa_reason"
                )

    def _update_labels(self):
        """Update the info labels."""
        filename = self._filtered_files[self.current_index]
        is_ann = self.progress.is_annotated(filename)

        self.file_label.config(text=f"{filename}  ({self.img_w}x{self.img_h})")

        if is_ann:
            self.annotated_badge.config(text="[ANNOTATED]", fg="#00ff00")
        else:
            self.annotated_badge.config(text="[NEW]", fg="#ffaa00")

        total = len(self.image_files)
        done = self.progress.annotated_count
        self.status_label.config(text=f"{done}/{total} annotated")

        filtered_total = len(self._filtered_files)
        if self._active_filter == "All images":
            self.counter_label.config(text=f"Image {self.current_index + 1} / {filtered_total}")
        else:
            self.counter_label.config(
                text=f"Image {self.current_index + 1} / {filtered_total}  [{self._active_filter}]"
            )

    # ── Mouse handlers ────────────────────────────────────────────────────────

    def _on_mouse_move(self, event):
        """Track mouse position for hover-based actions."""
        self._mouse_x = event.x
        self._mouse_y = event.y

    def _on_mouse_down_refocus(self, event):
        """Wrapper: handle mouse-down then return focus to root for key binds."""
        self._on_mouse_down(event)
        self.root.focus_set()

    def _on_mouse_down(self, event):
        self.drawing = True
        self.draw_start = (event.x, event.y)
        self.current_rect_id = self.canvas.create_rectangle(
            event.x, event.y, event.x, event.y,
            outline=BOX_COLOR_SELECTED, width=BOX_WIDTH, dash=(4, 2)
        )

    def _on_mouse_drag(self, event):
        if self.drawing and self.current_rect_id:
            self.canvas.coords(
                self.current_rect_id,
                self.draw_start[0], self.draw_start[1], event.x, event.y
            )

    def _on_mouse_up(self, event):
        if not self.drawing:
            return
        self.drawing = False

        x1_d, y1_d = self.draw_start
        x2_d, y2_d = event.x, event.y

        # Remove the temporary drawing rect
        if self.current_rect_id:
            self.canvas.delete(self.current_rect_id)
            self.current_rect_id = None

        # Convert display coords to image coords
        x1 = min(x1_d, x2_d) / self.scale
        y1 = min(y1_d, y2_d) / self.scale
        x2 = max(x1_d, x2_d) / self.scale
        y2 = max(y1_d, y2_d) / self.scale

        # Clamp to image bounds
        x1 = max(0, min(x1, self.img_w))
        y1 = max(0, min(y1, self.img_h))
        x2 = max(0, min(x2, self.img_w))
        y2 = max(0, min(y2, self.img_h))

        # Minimum box size filter (ignore tiny accidental clicks)
        if abs(x2 - x1) < 5 or abs(y2 - y1) < 5:
            return

        self.boxes.append([x1, y1, x2, y2])
        self._auto_save()
        self._redraw()

        # Hold Ctrl while drawing to suppress auto-advance (multi-box mode)
        if self.auto_advance.get() and not self._multi_box_mode:
            self._schedule_advance()

    def _on_right_click(self, event):
        """Delete the box closest to the right-click point."""
        if not self.boxes:
            return

        # Find which box the click is inside (display coords → image coords)
        click_x = event.x / self.scale
        click_y = event.y / self.scale

        for i, box in enumerate(self.boxes):
            x1, y1, x2, y2 = box
            if x1 <= click_x <= x2 and y1 <= click_y <= y2:
                self.boxes.pop(i)
                self._auto_save()
                self._redraw()
                return

    # ── Actions ───────────────────────────────────────────────────────────────

    def _resolve_image_path(self, filename: str) -> Path:
        """Return the path to an image, checking captures first then dataset."""
        cap = CAPTURES_DIR / filename
        if cap.exists():
            return cap
        return IMAGES_DIR / filename

    def _auto_save(self):
        """Immediately save current annotations to disk. Called on every change."""
        filename = self._filtered_files[self.current_index]
        stem = Path(filename).stem

        # Move image to dataset (copy then delete from captures)
        src = CAPTURES_DIR / filename
        dst = IMAGES_DIR / filename
        if src.exists():
            shutil.copy2(src, dst)
            src.unlink()
        elif not dst.exists():
            # Shouldn't happen, but guard against missing image
            return

        # Write YOLO label file (empty file = no class present)
        label_path = LABELS_DIR / (stem + ".txt")
        with open(label_path, "w") as f:
            for box in self.boxes:
                x1, y1, x2, y2 = box
                # Convert pixel coords to normalized center + size
                xc = ((x1 + x2) / 2) / self.img_w
                yc = ((y1 + y2) / 2) / self.img_h
                w = (x2 - x1) / self.img_w
                h = (y2 - y1) / self.img_h
                f.write(f"{CLASS_ID} {xc:.6f} {yc:.6f} {w:.6f} {h:.6f}\n")

        # Track progress
        self.progress.mark_annotated(filename, len(self.boxes))
        self._update_labels()

    def _schedule_advance(self):
        """Schedule an auto-advance, cancelling any pending one first."""
        self._cancel_advance()
        self._advance_timer = self.root.after(150, self._fire_advance)

    def _cancel_advance(self):
        """Cancel any pending auto-advance timer."""
        if self._advance_timer is not None:
            self.root.after_cancel(self._advance_timer)
            self._advance_timer = None

    def _fire_advance(self):
        """Auto-advance callback — skip to next unannotated image."""
        self._advance_timer = None
        self._skip_to_unannotated()

    def _prev_image(self):
        self._cancel_advance()
        if self.current_index > 0:
            self.current_index -= 1
            self._load_image()

    def _next_image(self):
        self._cancel_advance()
        if self.current_index < len(self._filtered_files) - 1:
            self.current_index += 1
            self._load_image()

    def _skip_no_class(self):
        """Mark current image as having no class (save empty annotation) and advance."""
        self.boxes.clear()
        self._auto_save()
        self._redraw()
        self._skip_to_unannotated()

    def _undo_last_box(self):
        if self.boxes:
            self.boxes.pop()
            self._auto_save()
            self._redraw()

    def _clear_boxes(self):
        self.boxes.clear()
        self._auto_save()
        self._redraw()

    def _accept_predictions(self):
        """Accept all AI prediction boxes as annotation labels and advance."""
        if not self.predictions:
            return
        for x1, y1, x2, y2, _conf in self.predictions:
            self.boxes.append([x1, y1, x2, y2])
        self._auto_save()
        self._redraw()
        if self.auto_advance.get():
            self._schedule_advance()

    def _accept_hovered_prediction(self):
        """Accept the single AI prediction box under the mouse cursor and advance."""
        if not self.predictions:
            return
        # Convert mouse display coords to image coords
        mx = self._mouse_x / self.scale
        my = self._mouse_y / self.scale
        for x1, y1, x2, y2, _conf in self.predictions:
            if x1 <= mx <= x2 and y1 <= my <= y2:
                self.boxes.append([x1, y1, x2, y2])
                self._auto_save()
                self._redraw()
                if self.auto_advance.get():
                    self._schedule_advance()
                return

    def _unmark_annotation(self):
        """Remove the current image from the dataset (un-annotate)."""
        filename = self._filtered_files[self.current_index]
        stem = Path(filename).stem

        # Restore image back to captures from dataset
        img_dst = IMAGES_DIR / filename
        cap_dst = CAPTURES_DIR / filename
        if img_dst.exists():
            if not cap_dst.exists():
                shutil.copy2(img_dst, cap_dst)
            img_dst.unlink()

        label_dst = LABELS_DIR / (stem + ".txt")
        if label_dst.exists():
            label_dst.unlink()

        self.progress.unmark(filename)
        self.boxes.clear()
        self._redraw()
        self._update_labels()

    def _skip_to_unannotated(self):
        """Jump to the next unannotated image in the filtered set."""
        start = self.current_index + 1
        for i in range(start, len(self._filtered_files)):
            if not self.progress.is_annotated(self._filtered_files[i]):
                self.current_index = i
                self._load_image()
                return
        for i in range(0, start):
            if not self.progress.is_annotated(self._filtered_files[i]):
                self.current_index = i
                self._load_image()
                return
        messagebox.showinfo("Done", "All images in this filter have been annotated!")

    def _open_bulk(self):
        """Open the bulk annotation window."""
        if self.model is None or self.inference_cache is None:
            messagebox.showwarning("No Model", "No YOLO model loaded — bulk annotation requires a trained model.")
            return
        BulkAnnotationWindow(self)

    def run(self):
        # Find first unannotated image in filtered set
        for i, f in enumerate(self._filtered_files):
            if not self.progress.is_annotated(f):
                self.current_index = i
                self._load_image()
                break
        else:
            # All annotated or empty filter — just show first
            if self._filtered_files:
                self.current_index = 0
                self._load_image()

        self.root.mainloop()


# ── Bulk Annotation Window ────────────────────────────────────────────────────
BULK_GRID_COLS = 4
BULK_GRID_ROWS = 4
BULK_GRID_SIZE = BULK_GRID_COLS * BULK_GRID_ROWS  # 16

BULK_PRESETS = [
    "All detections",
    "High confidence (>80%)",
    "Medium confidence (50-80%)",
    "Low confidence (25-50%)",
    "Single detection",
    "Multiple detections",
    "Custom range",
]


class BulkAnnotationWindow:
    """Full-screen 4x4 grid for rapid bulk accept/reject annotation.

    Uses cached AI predictions — no live inference needed.

    Left-click  = accept (save AI boxes as annotations, cell refills)
    Right-click = reject (skip, image stays unannotated for manual review, cell refills)
    """

    def __init__(self, parent_tool: AnnotationTool):
        self.parent = parent_tool
        self.progress = parent_tool.progress
        self.cache = parent_tool.inference_cache

        self.win = tk.Toplevel(parent_tool.root)
        self.win.title("Bulk Annotation")
        self.win.configure(bg="#2b2b2b")
        self.win.state("zoomed")  # maximize on Windows
        self.win.protocol("WM_DELETE_WINDOW", self._on_close)

        # Compute thumbnail size based on screen real estate
        screen_w = self.win.winfo_screenwidth()
        screen_h = self.win.winfo_screenheight()
        self.thumb_w = (screen_w - 60) // BULK_GRID_COLS - 14
        self.thumb_h = (screen_h - 180) // BULK_GRID_ROWS - 36

        # Queue state
        self._queue: list[str] = []
        self._queue_idx = 0
        self._accepted = 0
        self._rejected_count = 0
        self._undo_stack: list[dict] = []  # each entry: {action, fname, cell_idx, preds}

        self._build_ui()
        self._apply_filter()

    def _build_ui(self):
        # ── Top bar ───────────────────────────────────────────────────────
        top = tk.Frame(self.win, bg="#1e1e1e", padx=10, pady=6)
        top.pack(fill=tk.X)

        btn_style = {"font": ("Consolas", 10), "bg": "#3c3c3c", "fg": "#ffffff",
                      "activebackground": "#555555", "activeforeground": "#ffffff",
                      "relief": tk.FLAT, "padx": 8, "pady": 3}

        tk.Label(top, text="Filter:", font=("Consolas", 10),
                 bg="#1e1e1e", fg="#aaaaaa").pack(side=tk.LEFT)

        self.filter_var = tk.StringVar(value="All detections")
        filter_menu = ttk.Combobox(
            top, textvariable=self.filter_var, state="readonly",
            values=BULK_PRESETS, width=25, font=("Consolas", 10),
        )
        filter_menu.pack(side=tk.LEFT, padx=(5, 15))
        filter_menu.bind("<<ComboboxSelected>>", lambda e: self._on_preset_change())

        # Custom range inputs (always visible)
        tk.Label(top, text="Range:", font=("Consolas", 10),
                 bg="#1e1e1e", fg="#aaaaaa").pack(side=tk.LEFT, padx=(10, 0))
        self.custom_min_var = tk.StringVar(value="60")
        tk.Entry(top, textvariable=self.custom_min_var, width=5,
                 font=("Consolas", 10), bg="#333333", fg="#ffffff",
                 insertbackground="#ffffff").pack(side=tk.LEFT, padx=2)
        tk.Label(top, text="% to", font=("Consolas", 10),
                 bg="#1e1e1e", fg="#aaaaaa").pack(side=tk.LEFT)
        self.custom_max_var = tk.StringVar(value="100")
        tk.Entry(top, textvariable=self.custom_max_var, width=5,
                 font=("Consolas", 10), bg="#333333", fg="#ffffff",
                 insertbackground="#ffffff").pack(side=tk.LEFT, padx=2)
        tk.Label(top, text="%", font=("Consolas", 10),
                 bg="#1e1e1e", fg="#aaaaaa").pack(side=tk.LEFT)
        tk.Button(top, text="Apply", command=self._apply_custom, **btn_style).pack(
            side=tk.LEFT, padx=(5, 0))

        self.stats_label = tk.Label(
            top, text="", font=("Consolas", 10), bg="#1e1e1e", fg="#aaaaaa",
        )
        self.stats_label.pack(side=tk.RIGHT)

        # ── Legend ────────────────────────────────────────────────────────
        legend = tk.Frame(self.win, bg="#1e1e1e", padx=10, pady=3)
        legend.pack(fill=tk.X)
        tk.Label(
            legend,
            text="Left-click = Accept    |    Right-click = Reject    |    Ctrl+Z = Undo",
            font=("Consolas", 9), bg="#1e1e1e", fg="#888888",
        ).pack(side=tk.LEFT)

        btn_undo_style = {"font": ("Consolas", 10), "bg": "#3c3c3c", "fg": "#ffffff",
                          "activebackground": "#555555", "activeforeground": "#ffffff",
                          "relief": tk.FLAT, "padx": 8, "pady": 3}
        tk.Button(legend, text="Undo (Ctrl+Z)", command=self._undo, **btn_undo_style).pack(
            side=tk.RIGHT, padx=2)

        self.win.bind("<Control-z>", lambda e: self._undo())
        self.win.bind("<Control-Z>", lambda e: self._undo())

        # ── Grid ──────────────────────────────────────────────────────────
        self.grid_frame = tk.Frame(self.win, bg="#2b2b2b", padx=5, pady=5)
        self.grid_frame.pack(fill=tk.BOTH, expand=True)

        self._cells: list[dict] = []
        for row in range(BULK_GRID_ROWS):
            self.grid_frame.rowconfigure(row, weight=1)
            for col in range(BULK_GRID_COLS):
                self.grid_frame.columnconfigure(col, weight=1)

                cell_frame = tk.Frame(
                    self.grid_frame, bg="#1a1a1a",
                    highlightbackground="#333", highlightthickness=1,
                )
                cell_frame.grid(row=row, column=col, padx=3, pady=3, sticky="nsew")

                cvs = tk.Canvas(
                    cell_frame, bg="#000000", highlightthickness=0,
                    cursor="hand2",
                )
                cvs.pack(fill=tk.BOTH, expand=True, padx=2, pady=2)

                lbl = tk.Label(
                    cell_frame, text="", font=("Consolas", 8),
                    bg="#1a1a1a", fg="#aaaaaa",
                )
                lbl.pack()

                self._cells.append({
                    "frame": cell_frame, "canvas": cvs, "label": lbl,
                    "filename": None, "predictions": [], "tk_img": None,
                })

    # ── Filter logic ──────────────────────────────────────────────────────

    def _get_filter_params(self):
        """Return (min_conf, max_conf, det_count) for the active filter.

        det_count: None = any, 1 = exactly one, -1 = two or more.
        """
        preset = self.filter_var.get()
        if preset == "High confidence (>80%)":
            return (0.80, 1.0, None)
        elif preset == "Medium confidence (50-80%)":
            return (0.50, 0.80, None)
        elif preset == "Low confidence (25-50%)":
            return (0.25, 0.50, None)
        elif preset == "Single detection":
            return (PREDICTION_CONF_THRESH, 1.0, 1)
        elif preset == "Multiple detections":
            return (PREDICTION_CONF_THRESH, 1.0, -1)
        elif preset == "Custom range":
            return self._parse_custom_range()
        # "All detections" or fallback
        return (PREDICTION_CONF_THRESH, 1.0, None)

    def _parse_custom_range(self):
        try:
            mn = float(self.custom_min_var.get()) / 100.0
        except ValueError:
            mn = 0.25
        try:
            mx = float(self.custom_max_var.get()) / 100.0
        except ValueError:
            mx = 1.0
        return (mn, mx, None)

    def _build_queue(self) -> list[str]:
        """Build filtered candidate list from cached predictions."""
        min_conf, max_conf, det_count = self._get_filter_params()
        queue = []
        for fname in self.parent.image_files:
            if self.progress.is_annotated(fname):
                continue
            cached = self.cache.get(fname)
            if not cached or len(cached) == 0:
                continue
            # Detection count filter
            num_det = len(cached)
            if det_count == 1 and num_det != 1:
                continue
            if det_count == -1 and num_det < 2:
                continue
            # Confidence filter on highest-confidence detection
            max_c = max(p[4] for p in cached)
            if max_c < min_conf or max_c > max_conf:
                continue
            queue.append(fname)
        return queue

    def _on_preset_change(self):
        if self.filter_var.get() != "Custom range":
            self._apply_filter()

    def _apply_custom(self):
        self.filter_var.set("Custom range")
        self._apply_filter()

    def _apply_filter(self):
        """Rebuild the queue and fill the entire grid."""
        self._queue = self._build_queue()
        self._queue_idx = 0
        self._accepted = 0
        self._rejected_count = 0
        for i in range(BULK_GRID_SIZE):
            self._fill_cell(i)
        self._update_stats()

    # ── Cell display ──────────────────────────────────────────────────────

    def _fill_cell(self, cell_idx: int):
        """Pop the next image from the queue into a grid cell."""
        cell = self._cells[cell_idx]
        cvs = cell["canvas"]
        lbl = cell["label"]

        cvs.unbind("<Button-1>")
        cvs.unbind("<Button-3>")

        if self._queue_idx >= len(self._queue):
            # No more images for this cell
            cvs.delete("all")
            cvs.config(bg="#111111")
            lbl.config(text="")
            cell["filename"] = None
            cell["predictions"] = []
            cell["tk_img"] = None
            return

        fname = self._queue[self._queue_idx]
        self._queue_idx += 1
        cell["filename"] = fname

        filepath = CAPTURES_DIR / fname
        pil_img = Image.open(filepath)
        img_w, img_h = pil_img.size

        # Get cached predictions
        cached = self.cache.get(fname) or []
        preds = [tuple(p) for p in cached]
        cell["predictions"] = preds

        # Draw prediction boxes on a copy
        draw_img = pil_img.copy()
        draw = ImageDraw.Draw(draw_img)
        for x1, y1, x2, y2, conf in preds:
            draw.rectangle([x1, y1, x2, y2], outline=(0, 204, 204), width=2)
            draw.text((x1 + 2, y1 - 12), f"{conf:.0%}", fill=(0, 204, 204))

        # Scale to thumbnail
        scale = min(self.thumb_w / img_w, self.thumb_h / img_h)
        tw = max(1, int(img_w * scale))
        th = max(1, int(img_h * scale))
        thumb = draw_img.resize((tw, th), Image.LANCZOS)

        tk_img = ImageTk.PhotoImage(thumb)
        cell["tk_img"] = tk_img  # prevent GC

        cvs.config(width=tw, height=th)
        cvs.delete("all")
        cvs.create_image(0, 0, anchor=tk.NW, image=tk_img)

        max_conf = max((p[4] for p in preds), default=0)
        lbl.config(text=f"{fname}  ({len(preds)} det, {max_conf:.0%})")
        cell["frame"].config(highlightbackground="#333", highlightthickness=1)

        # Bind accept / reject
        cvs.bind("<Button-1>", lambda e, ci=cell_idx: self._accept_cell(ci))
        cvs.bind("<Button-3>", lambda e, ci=cell_idx: self._reject_cell(ci))

    # ── Accept / Reject ───────────────────────────────────────────────────

    def _accept_cell(self, cell_idx: int):
        """Accept AI predictions for this cell — save as YOLO annotation."""
        cell = self._cells[cell_idx]
        fname = cell["filename"]
        if not fname:
            return
        preds = cell["predictions"]
        if not preds:
            return

        filepath = CAPTURES_DIR / fname
        pil_img = Image.open(filepath)
        img_w, img_h = pil_img.size
        stem = Path(fname).stem

        # Copy image to dataset
        shutil.copy2(filepath, IMAGES_DIR / fname)

        # Write YOLO label file
        label_path = LABELS_DIR / (stem + ".txt")
        with open(label_path, "w") as f:
            for x1, y1, x2, y2, _conf in preds:
                xc = ((x1 + x2) / 2) / img_w
                yc = ((y1 + y2) / 2) / img_h
                w = (x2 - x1) / img_w
                h = (y2 - y1) / img_h
                f.write(f"{CLASS_ID} {xc:.6f} {yc:.6f} {w:.6f} {h:.6f}\n")

        self.progress.mark_annotated(fname, len(preds))
        self._accepted += 1
        self._undo_stack.append({
            "action": "accept", "fname": fname, "cell_idx": cell_idx,
        })

        # Flash green then refill
        cell["frame"].config(highlightbackground="#00ff00", highlightthickness=3)
        self.win.after(120, lambda: self._refill_cell(cell_idx))

    def _reject_cell(self, cell_idx: int):
        """Reject — image stays unannotated, cell refills with next match."""
        cell = self._cells[cell_idx]
        if not cell["filename"]:
            return
        self._rejected_count += 1
        self._undo_stack.append({
            "action": "reject", "fname": cell["filename"], "cell_idx": cell_idx,
        })

        # Flash red then refill
        cell["frame"].config(highlightbackground="#ff4444", highlightthickness=3)
        self.win.after(120, lambda: self._refill_cell(cell_idx))

    def _undo(self):
        """Undo the last accept or reject action."""
        if not self._undo_stack:
            return
        entry = self._undo_stack.pop()
        fname = entry["fname"]
        cell_idx = entry["cell_idx"]

        if entry["action"] == "accept":
            # Remove annotation from dataset
            stem = Path(fname).stem
            img_dst = IMAGES_DIR / fname
            label_dst = LABELS_DIR / (stem + ".txt")
            if img_dst.exists():
                img_dst.unlink()
            if label_dst.exists():
                label_dst.unlink()
            self.progress.unmark(fname)
            self._accepted -= 1
        elif entry["action"] == "reject":
            self._rejected_count -= 1

        # Put the image back into the cell so the user can re-decide
        # Decrement queue index if the cell currently has a queued image
        # (push back the image that replaced it)
        current_fname = self._cells[cell_idx]["filename"]
        if current_fname is not None:
            self._queue_idx -= 1

        # Override the cell with the undone image
        self._cells[cell_idx]["filename"] = fname
        self._show_image_in_cell(cell_idx, fname)
        self._update_stats()

    def _show_image_in_cell(self, cell_idx: int, fname: str):
        """Display a specific image in a cell (used by undo)."""
        cell = self._cells[cell_idx]
        cvs = cell["canvas"]
        lbl = cell["label"]

        filepath = CAPTURES_DIR / fname
        pil_img = Image.open(filepath)
        img_w, img_h = pil_img.size

        cached = self.cache.get(fname) or []
        preds = [tuple(p) for p in cached]
        cell["predictions"] = preds

        draw_img = pil_img.copy()
        draw = ImageDraw.Draw(draw_img)
        for x1, y1, x2, y2, conf in preds:
            draw.rectangle([x1, y1, x2, y2], outline=(0, 204, 204), width=2)
            draw.text((x1 + 2, y1 - 12), f"{conf:.0%}", fill=(0, 204, 204))

        scale = min(self.thumb_w / img_w, self.thumb_h / img_h)
        tw = max(1, int(img_w * scale))
        th = max(1, int(img_h * scale))
        thumb = draw_img.resize((tw, th), Image.LANCZOS)

        tk_img = ImageTk.PhotoImage(thumb)
        cell["tk_img"] = tk_img

        cvs.config(width=tw, height=th)
        cvs.delete("all")
        cvs.create_image(0, 0, anchor=tk.NW, image=tk_img)

        max_conf = max((p[4] for p in preds), default=0)
        lbl.config(text=f"{fname}  ({len(preds)} det, {max_conf:.0%})")
        cell["frame"].config(highlightbackground="#ffaa00", highlightthickness=2)

        cvs.bind("<Button-1>", lambda e, ci=cell_idx: self._accept_cell(ci))
        cvs.bind("<Button-3>", lambda e, ci=cell_idx: self._reject_cell(ci))

    def _refill_cell(self, cell_idx: int):
        self._fill_cell(cell_idx)
        self._update_stats()

    def _update_stats(self):
        remaining = len(self._queue) - self._queue_idx
        total = len(self._queue)
        self.stats_label.config(
            text=f"{total} matches  |  {remaining} remaining  |  "
                 f"Accepted: {self._accepted}  |  Skipped: {self._rejected_count}"
        )

    def _on_close(self):
        # Refresh parent's labels in case annotations changed
        self.parent._update_labels()
        self.win.destroy()


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print(f"YOLO Annotation Tool")
    print(f"  Captures dir : {CAPTURES_DIR}")
    print(f"  Dataset dir  : {DATASET_DIR}")
    print(f"  Class        : {CLASS_ID} = '{CLASS_NAME}'")
    print()
    print("Controls:")
    print("  LMB drag     = draw box")
    print("  Ctrl+drag    = draw box (no auto-advance, multi-box)")
    print("  RMB on box   = delete box")
    print("  A/D or ←/→   = prev/next image")
    print("  Space        = skip (no class in image)")
    print("  Z            = undo last box")
    print("  C            = clear all boxes")
    print("  Enter        = accept AI prediction boxes")
    print("  B            = open bulk annotation window")
    print("  Esc          = quit")
    print("  Auto-save is always on — every change saves immediately")
    print()

    tool = AnnotationTool()
    tool.run()


if __name__ == "__main__":
    main()
